dvisionlab/ditto

- app/library/dicom/utils.js
correct import of larvitar with Vue as variable
> fix larvitar 1.5.10 issue

- app/library/data-types/dicom/thumbnail/String.vue
Icona in overlay a thumbnail lista study per segnalare eventuali anomalie retrieve
> Warning icon thumb

- app/library/dicom/render/CanvasData.vue
[TD-851](https://dicomvision.atlassian.net/browse/TD-851)
[TD-851]: https://dicomvision.atlassian.net/browse/TD-851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: viewport info slice or frame

- app/library/dicom/utils.js
Aggiunta la funzione per cachare immagini in modo da evitare i lag soprattutto nei multiframe
> fix: cache images

- app/library/dicom/multiframe/CinematicTool.vue
- app/library/dicom/render/Canvas.vue
FIxes on slider: just changed two parameters. Seems working, need to be tested with bigger multiframe
> Fix slider

- app/library/dicom/defaults.js
- app/library/dicom/multiframe/CinematicTool.vue
- app/library/dicom/render/Canvas.vue
- app/library/dicom/render/CanvasData.vue
- app/library/dicom/utils.js
Support for new scroll system, frame by frame scroll, frame multiframe player and scrolling modality information
> 4d tool fixing

- app/library/dicom/render/Canvas.vue
[TD-985](https://dicomvision.atlassian.net/browse/TD-985)
[TD-985]: https://dicomvision.atlassian.net/browse/TD-985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: plot container

- app/library/dicom/render/Canvas.vue
Controllare se nelle 4D il click della rotellina cambia tipologia scroll e se nel caso delle NON 4d tutto il click della rotellina non genera errori
> fix: midclick 

- app/library/dicom/import/Component.vue
- app/library/dicom/import/Wrapper.vue
- app/library/dicom/import/steps/Step1.vue
- app/library/dicom/import/steps/Step3.vue
[TD-1049](https://dicomvision.atlassian.net/browse/TD-1049)
[TD-1049]: https://dicomvision.atlassian.net/browse/TD-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: improve ui & ux of local import steps

- app/library/dicom/render/Canvas.vue
[TD-1087](https://dicomvision.atlassian.net/browse/TD-1087)
[TD-1059](https://dicomvision.atlassian.net/browse/TD-1059)
[TD-1087]: https://dicomvision.atlassian.net/browse/TD-1087?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[TD-1059]: https://dicomvision.atlassian.net/browse/TD-1059?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: always first slice and vue slider console error

- app/library/auth/components/AccountPanel.vue
[TD-1082](https://dicomvision.atlassian.net/browse/TD-1082)
[TD-1082]: https://dicomvision.atlassian.net/browse/TD-1082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: show build_id

- app/library/auth/components/AccountPanel.vue
[TD-1076](https://dicomvision.atlassian.net/browse/TD-1076)
[TD-1076]: https://dicomvision.atlassian.net/browse/TD-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: download admin manual

- app/library/auth/components/AccountPanel.vue
[TD-1076](https://dicomvision.atlassian.net/browse/TD-1076)
[TD-1076]: https://dicomvision.atlassian.net/browse/TD-1076?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: manual path from env

- app/library/auth/components/AccountPanel.vue
[TD-1014](https://dicomvision.atlassian.net/browse/TD-1014)
[TD-1014]: https://dicomvision.atlassian.net/browse/TD-1014?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: remove build id from account panel

- app/library/dicom/utils.js
[TD-1104](https://dicomvision.atlassian.net/browse/TD-1104)
[TD-1104]: https://dicomvision.atlassian.net/browse/TD-1104?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: downloaded series cached

- app/library/auth/components/AccountPanel.vue
- app/library/auth/components/LoginForm.vue
- app/library/auth/http.js
- app/library/auth/persist.js
- app/library/auth/plugin.js
- app/library/auth/router.js
- app/library/auth/store.js
- app/library/auth/utils.js
[TD-764](https://dicomvision.atlassian.net/browse/TD-764)
[TD-764]: https://dicomvision.atlassian.net/browse/TD-764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: session based auth

- app/library/dicom/import/steps/Step2.vue
[TD-1120](https://dicomvision.atlassian.net/browse/TD-1120)
[TD-1120]: https://dicomvision.atlassian.net/browse/TD-1120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: Alert on anonymizing

- app/library/dicom/import/steps/Step2.vue
- app/library/dicom/render/Canvas.vue
- app/library/dicom/utils.js
[TD-1145](https://dicomvision.atlassian.net/browse/TD-1145)
[TD-1145]: https://dicomvision.atlassian.net/browse/TD-1145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: clear series and annotations cache only on dashboard deflag

- app/library/dicom/import/Component.vue
- app/library/dicom/multiframe/CinematicTool.vue
- app/library/dicom/render/Canvas.vue
- app/library/dicom/utils.js
[TD-967](https://dicomvision.atlassian.net/browse/TD-967)
[TD-967]: https://dicomvision.atlassian.net/browse/TD-967?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: multiframe caching, fps instead of ms and autoplay looped in cine modality for multiframe

- app/library/auth/components/AccountPanel.vue
[TD-1144](https://dicomvision.atlassian.net/browse/TD-1144)
[TD-1144]: https://dicomvision.atlassian.net/browse/TD-1144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: qa label

- app/library/auth/router.js
used to show the user and demo badge
> fix: fix isDemo and isAdmin on reload

- app/library/auth/components/AccountPanel.vue
- app/library/dicom/import/Wrapper.vue
- app/library/dicom/import/steps/Step1.vue
- app/library/dicom/multiframe/CinematicTool.vue
- app/library/dicom/pacs/import/Wrapper.vue
[TD-989](https://dicomvision.atlassian.net/browse/TD-989)
tema dark: ombreggiature e overlay per rendere più chiare le dialog e i menu con tema dark
[TD-989]: https://dicomvision.atlassian.net/browse/TD-989?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: overlay fix on dialog and menu

- app/library/auth/components/AccountPanel.vue
- app/library/auth/http.js
- app/library/auth/router.js
- app/library/auth/store.js
- app/library/dicom/import/Component.vue
- app/library/dicom/import/steps/Step3.vue
- app/library/wireframes/DoubleNavigation.vue
[TD-1159](https://dicomvision.atlassian.net/browse/TD-1159)
[TD-1159]: https://dicomvision.atlassian.net/browse/TD-1159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: upload link

- app/library/dicom/utils.js
Soluzione provvisoria per l'anonimizzazione lato client. I dati sensibili sono anonimizzati, crittati tramite un hash code,generato da una funzione. Viene fatta una prima anon tramite larvitar che anonimizza i dati sensibili per ogni immagine. Questa viene sovrascritta parzialmente dagli hash generati precedentemente per ogni serie dello studio.
> Anonymization client side

- app/library/dicom/utils.js
Before:
https://github.com/user-attachments/assets/852942c4-eca9-490c-b26a-e61384cde7e3
After:
https://github.com/user-attachments/assets/ddda6948-24ab-4c5e-8dfd-6e5e3af460b0
> fix: multiframe reupload
